- hosts: all
  tasks:
    - name: set timezone
      timezone:
        name: Europe/Berlin
    - name: install packages
      apt:
        name: "{{ item }}"
      with_items:
        - ntp
        - nginx
        - git
        - gawk
        - g++
        - gcc
        - make
        - libc6-dev
        - zlib1g-dev
        - libyaml-dev
        - libsqlite3-dev
        - sqlite3
        - autoconf
        - libgmp-dev
        - libgdbm-dev
        - libncurses5-dev
        - automake
        - libtool
        - bison
        - pkg-config
        - libffi-dev
        - libgmp-dev
        - libreadline6-dev
        - libssl-dev
        - libmysqlclient-dev
        - mysql-client
        - mysql-server
        - python-mysqldb
        - apticron
        - postfix
        - mailutils
        - procmail
        - mutt
