- hosts: all
  tasks:
    - name: add user flohmarkthelfer
      user:
        name: flohmarkthelfer
        shell: /bin/bash
    - name: Set authorized key for user flohmarkthelfer copying it from current user
      authorized_key:
        user: flohmarkthelfer
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    - name: check rvm
      command: $HOME/.rvm/bin/rvm -v
      register: rvm_check
      ignore_errors: true
      become: true
      become_user: flohmarkthelfer
    - name: install rvm
      shell: |
        gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
        curl -sSL https://get.rvm.io | bash -s stable
        $HOME/.rvm/bin/rvm autolibs fail
      become: true
      become_user: flohmarkthelfer
      when: rvm_check is failed
    - name: update rvm
      command: $HOME/.rvm/bin/rvm update
      become: true
      become_user: flohmarkthelfer
      when: rvm_check is succeeded
    - name: install ruby
      command: $HOME/.rvm/bin/rvm install ruby-2.7.3 --default
      become: true
      become_user: flohmarkthelfer
    - name: install bundler
      command: $HOME/.rvm/bin/rvm all do gem install bundler
      become: true
      become_user: flohmarkthelfer
    - name: create shared config folders
      file:
        path: /home/flohmarkthelfer/www/shared/config/settings/brands
        state: directory
        group: flohmarkthelfer
        owner: flohmarkthelfer
    - name: create shared database config
      copy:
        content: |
          production:
            adapter: mysql2
            encoding: utf8
            database: flohmarkthelfer
            username: flohmarkthelfer
            password: flohmarkthelfer
            host: 127.0.0.1
            port: 3306
            secure_auth: false
        dest: /home/flohmarkthelfer/www/shared/config/database.yml
        group: flohmarkthelfer
        owner: flohmarkthelfer
    #- name: create shared secret config - this neeeds to be generated on server with bundle exec rake secret
    #  copy:
    #    content: |
    #      production:
    #        secret_key_base: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    #    dest: /home/flohmarkthelfer/www/shared/config/secrets.yml
    #    group: flohmarkthelfer
    #    owner: flohmarkthelfer
    - name: create backup folders
      file:
        path: /home/flohmarkthelfer/www/shared/backup/db
        state: directory
        group: flohmarkthelfer
        owner: flohmarkthelfer
    - name: create pids folders
      file:
        path: /home/flohmarkthelfer/www/shared/tmp/pids
        state: directory
        group: flohmarkthelfer
        owner: flohmarkthelfer
    - name: create database
      mysql_db:
        encoding: utf8
        name: flohmarkthelfer
    # stopped working with error: 'database' is an invalid keyword argument for this function
    # - name: create db user
    #  mysql_user:
    #    name: flohmarkthelfer
    #    password: flohmarkthelfer
    #    priv: 'flohmarkthelfer.*:ALL'
    #    state: present
    - name: install systemd config for flohmarkthelfer puma server
      copy:
        content: |
          [Unit]
          Description=Flohmarkthelfer web service
          After=network.target

          [Service]
          Type=simple
          User=flohmarkthelfer
          Group=flohmarkthelfer
          WorkingDirectory=/home/flohmarkthelfer/www/current
          ExecStart=/home/flohmarkthelfer/.rvm/bin/rvm 2.7.3 do bundle exec puma -C /home/flohmarkthelfer/www/shared/config/puma.rb
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/flohmarkthelfer.service
      notify: restart web service
    - name: install systemd config for flohmarkthelfer worker
      copy:
        content: |
          [Unit]
          Description=Flohmarkthelfer worker service
          After=network.target

          [Service]
          Type=simple
          User=flohmarkthelfer
          Group=flohmarkthelfer
          Environment='RAILS_ENV=production'
          WorkingDirectory=/home/flohmarkthelfer/www/current
          ExecStart=/home/flohmarkthelfer/.rvm/bin/rvm 2.7.3 do bundle exec bin/delayed_job
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/flohmarkthelfer-worker.service
      notify: restart worker service
  handlers:
    - name: restart web service
      systemd:
        name: flohmarkthelfer
        state: restarted
        daemon_reload: yes
    - name: restart worker service
      systemd:
        name: flohmarkthelfer-worker
        state: restarted
        daemon_reload: yes
